%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-ur-client-library
Version:        0.3.2
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS ur_client_library package

License:        Apache-2.0
URL:            http://wiki.ros.org/ur_client_library
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-noetic-catkin
BuildRequires:  boost-devel
BuildRequires:  boost-python3-devel
BuildRequires:  cmake
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
Standalone C++ library for accessing Universal Robots interfaces. This has been
forked off the ur_robot_driver.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/noetic

%changelog
* Wed Sep 15 2021 Felix Exner <exner@fzi.de> - 0.3.2-1
- Autogenerated by Bloom

* Tue Jun 22 2021 Felix Exner <exner@fzi.de> - 0.3.1-1
- Autogenerated by Bloom

* Fri Jun 18 2021 Felix Exner <exner@fzi.de> - 0.3.0-1
- Autogenerated by Bloom

* Mon May 31 2021 Felix Exner <exner@fzi.de> - 0.2.2-1
- Autogenerated by Bloom

* Mon May 03 2021 Felix Exner <exner@fzi.de> - 0.2.0-1
- Autogenerated by Bloom

* Wed Sep 16 2020 Felix Exner <exner@fzi.de> - 0.1.1-1
- Autogenerated by Bloom

